# Generated by Django 4.2.17 on 2024-12-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
