# Generated by Django 4.2.17 on 2024-12-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_bookingtime_bookingtable_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='USER',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='complainttable',
            name='reply',
        ),
        migrations.CreateModel(
            name='supplycoprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplyid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('openningtime', models.TimeField(blank=True, null=True)),
                ('closingtime', models.TimeField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.logintable')),
            ],
        ),
    ]
