# Generated by Django 4.2.17 on 2024-12-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_user_feedbacktable_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplycoprofile',
            old_name='supplyid',
            new_name='supplycoid',
        ),
        migrations.RemoveField(
            model_name='supplycoprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='supplycoprofile',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
