# Generated by Django 4.2.17 on 2024-12-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_supplyid_supplycoprofile_supplycoid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
