# Generated by Django 4.2.17 on 2024-12-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_remove_stocktable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktable',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktable',
            name='stockid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
