# Generated by Django 4.2.17 on 2024-12-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_stocktable_quantity_alter_stocktable_stockid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookingtable',
            new_name='shopBookingtable',
        ),
        migrations.AddField(
            model_name='producttable',
            name='SUPPLYCO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.shopprofile'),
        ),
        migrations.CreateModel(
            name='supplycoBookingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('PRODUCT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.producttable')),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.usertable')),
            ],
        ),
    ]
