# Generated by Django 4.2.17 on 2024-12-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_rename_bookingtable_shopbookingtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='marketprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
