# Generated by Django 4.2.17 on 2024-12-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_producttable_marketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='SUPPLYCO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.supplycoprofile'),
        ),
    ]
