# Generated by Django 4.2.17 on 2024-12-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_producttable_supplyco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbookingtable',
            name='PRODUCT',
        ),
        migrations.AddField(
            model_name='shopbookingtable',
            name='STOCK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.stocktable'),
        ),
    ]
