# Generated by Django 4.2.17 on 2024-12-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_remove_shopbookingtable_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtable',
            name='datetime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
