# Generated by Django 4.2.17 on 2024-12-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_supplycobookingtable_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='userid',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='address',
        ),
    ]
