# Generated by Django 4.2.17 on 2024-12-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_rename_userid_usertable_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='username',
        ),
    ]
