
from django.urls import path
from .views import *

urlpatterns = [
    path('adminhome',adminhome.as_view(),name='adminhome'),
    path('digitalcard',digitalcard.as_view(),name='digitalcard'),
    path('',adminlogin.as_view(),name='adminlogin'),
    path('verifyshop',verifyshop.as_view(),name='verifyshop'),
    path('approve_shop/<int:login_id>',approve_shop.as_view(),name='approve_shop'),
    path('reject_shop/<int:login_id>',reject_shop.as_view(),name='reject_shop'),
    path('complaint',complaint.as_view(),name='complaint'),
    path('complaintreply/<int:pk>',complaintreply.as_view(),name='complaintreply'),
    path('feedback',feedback.as_view(),name='feedback'),
    path('deliverystatus',deliverystatus.as_view(),name='deliverystatus'),
    path('rationhome',rationhome.as_view(),name='rationhome'),
    path('addandupdatestock',addandupdatestock.as_view(),name='addandupdatestock'),
    path('addstock',addstock.as_view(),name='addstock'),
    path('editstock/<int:stock_id>',editstock.as_view(),name='editstock'),
    path('deletestock/<int:stock_id>',deletestock.as_view(),name='deletestock'),
    path('rationshoplogin',rationshoplogin.as_view(),name='rationshoplogin'),
    path('shopregistration',shopregistration.as_view(),name='shopregistration'),
    path('shopopeningandclosingstatus',shopopeningandclosingstatus.as_view(),name='shopopeningandclosingstatus'),
    path('stockbooking',stockbooking.as_view(),name='stockbooking'),
    path('productbooking',productbooking.as_view(),name='productbooking'),
    path('addandmanageproduct',addandmanageproduct.as_view(),name='addandmanageproduct'),
    path('addproduct',addproduct.as_view(),name='addproduct'),
    path('editproduct/<int:productid>',editproduct.as_view(),name='editproduct'),
    path('deleteproduct/<int:productid>',deleteproduct.as_view(),name='deleteproduct'),
    path('managenotification',managenotification.as_view(),name='managenotification'),
    path('supplycologin',supplycologin.as_view(),name='supplycologin'),
    path('viewusers',viewusers.as_view(),name='viewusers'),
    path('supplycohome',supplycohome.as_view(),name='supplycohome'),
    path('addandmanagesupplyco',addandmanagesupplyco.as_view(),name='addandmanagesupplyco'),
    path('approve_supplyco/<int:login_id>',approve_supplyco.as_view(),name='approve_supplyco'),
    path('reject_supplyco/<int:login_id>',reject_supplyco.as_view(),name='reject_supplyco'),
    path('viewproduct/<int:bookingid>',viewproduct.as_view(),name='viewproduct'),

    # ////////////////////////////////////// API /////////////////////////////////////////////////
    path('SignupApi',SignupApi.as_view(),name='SignupApi'),
    path('LoginApi',LoginApi.as_view(),name='LoginApi'),
    path('ProfileApi',ProfileApi.as_view(),name='ProfileApi'),
    path('EditprofileApi',EditprofileApi.as_view(),name='EditprofileApi'),
    path('FeedbackApi',FeedbackApi.as_view(),name='FeedbackApi'),
    path('ViewstockApi',ViewstockApi.as_view(),name='ViewstockApi'),
    path('StockApi',StockApi.as_view(),name='StockApi'),
    path('ShoporderApi',ShoporderApi.as_view(),name='ShoporderApi'),
    path('ShoptimeApi',ShoptimeApi.as_view(),name='ShoptimeApi'),
    path('ViewproductApi',ViewproductApi.as_view(),name='ViewproductApi'),
    path('ProductApi',ProductApi.as_view(),name='ProductApi'),
    path('SupplycoordersApi',SupplycoordersApi.as_view(),name='SupplycoordersApi'),
    path('NotificatinsApi',NotificatinsApi.as_view(),name='NotificatinsApi'),

]
